# Generated by Django 4.1.7 on 2023-03-28 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_de_receta', models.CharField(max_length=30)),
                ('Autor', models.CharField(max_length=15)),
                ('Rendimiento', models.CharField(max_length=10)),
                ('Horas_de_prepracion', models.CharField(max_length=50)),
                ('Preparacion', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recetas')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
