# Generated by Django 4.1.7 on 2023-03-29 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRodriguezFinal', '0003_alter_profile_image_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='avatar',
        ),
    ]
