# Generated by Django 4.1.7 on 2023-03-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRodriguezFinal', '0004_rename_image_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receta'),
        ),
    ]
