# Generated by Django 4.1.7 on 2023-03-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRodriguezFinal', '0005_alter_receta_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recetas'),
        ),
    ]
